import jsPDF from 'jspdf';
import type {
  CalculatorInput,
  CalculatorResult,
  ChannelComparison,
} from './types';
import type { CostSlice, CutListResult } from './calculator';
import { ANIMAL_PROFILES } from './animalDefaults';
import {
  fmtCurrency,
  fmtCurrency2,
  fmtLbs,
  fmtLbs1,
  fmtPct,
  todayIso,
} from './formatters';

interface PdfArgs {
  input: CalculatorInput;
  result: CalculatorResult;
  channels: ChannelComparison[];
  slices: CostSlice[];
  cutList?: CutListResult | null;
}

const NAVY: [number, number, number] = [27, 58, 107];
const GOLD: [number, number, number] = [181, 150, 90];
const INK: [number, number, number] = [26, 26, 26];
const MUTED: [number, number, number] = [107, 107, 107];
const RULE: [number, number, number] = [229, 224, 213];
const PAPER: [number, number, number] = [248, 246, 241];

export function exportPricingPdf({
  input,
  result,
  channels,
  slices,
  cutList,
}: PdfArgs): void {
  const animal = input.step1.animal ? ANIMAL_PROFILES[input.step1.animal] : null;
  const animalLabel = animal?.label ?? 'Pricing';

  const doc = new jsPDF({ unit: 'pt', format: 'letter', orientation: 'portrait' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFillColor(...PAPER);
  doc.rect(0, 0, W, doc.internal.pageSize.getHeight(), 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...GOLD);
  doc.text('FROM THE FARM  ·  PRICING REPORT', margin, y);
  doc.setTextColor(...MUTED);
  doc.text(todayIso().toUpperCase(), W - margin, y, { align: 'right' });
  y += 22;

  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.6);
  doc.line(margin, y, W - margin, y);
  y += 28;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...GOLD);
  doc.text(`${animalLabel.toUpperCase()}  ·  YOUR RECOMMENDED PRICE`, margin, y);
  y += 14;

  const priceText = fmtCurrency2(result.recommendedPricePerLb);
  doc.setFontSize(54);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  const priceWidth = doc.getTextWidth(priceText);
  doc.text(priceText, margin, y + 38);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text('/ lb', margin + priceWidth + 12, y + 38);
  y += 64;

  drawKpiStrip(doc, margin, y, W - margin * 2, [
    { label: 'COST PER LB', value: fmtCurrency2(result.costPerLb) },
    { label: 'PROFIT MARGIN', value: fmtPct(result.marginPct) },
    { label: 'PROFIT THIS BATCH', value: fmtCurrency(result.netProfit) },
    { label: 'PACKAGED LBS', value: fmtLbs(result.totalPackagedLbs) },
  ]);
  y += 56;

  y = drawSectionHeading(doc, margin, y, 'WHERE THE MONEY GOES');
  y = drawCostSlices(doc, margin, y, W - margin * 2, slices, result.totalCosts);
  y += 24;

  y = drawSectionHeading(doc, margin, y, 'HOW CHANNELS COMPARE');
  y = drawChannels(doc, margin, y, W - margin * 2, channels);
  y += 24;

  y = drawSectionHeading(doc, margin, y, 'HOW WE GOT THERE');
  y = drawAssumptions(doc, margin, y, W - margin * 2, input);
  y += 16;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    'Generated by the From The Farm Pricing Calculator. Save this and update it as your costs change.',
    W / 2,
    doc.internal.pageSize.getHeight() - 32,
    { align: 'center' },
  );

  if (cutList && cutList.groups.length > 0) {
    drawCutListPage(doc, cutList, animalLabel);
  }

  const filename = `ftf-pricing-${(input.step1.animal ?? 'meat')}-${todayIso()}.pdf`;
  doc.save(filename);
}

function drawCutListPage(
  doc: jsPDF,
  cutList: CutListResult,
  animalLabel: string,
): void {
  doc.addPage();
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = margin;

  doc.setFillColor(...PAPER);
  doc.rect(0, 0, W, H, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...GOLD);
  doc.text('FROM THE FARM  ·  PRICING REPORT', margin, y);
  doc.setTextColor(...MUTED);
  doc.text(todayIso().toUpperCase(), W - margin, y, { align: 'right' });
  y += 22;

  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.6);
  doc.line(margin, y, W - margin, y);
  y += 28;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...GOLD);
  doc.text(`${animalLabel.toUpperCase()}  ·  RETAIL CUT LIST`, margin, y);
  y += 14;

  doc.setFontSize(20);
  doc.setTextColor(...NAVY);
  doc.text('Per-cut pricing', margin, y + 18);
  y += 36;

  const recommendedAvg =
    cutList.totalLbs > 0 ? cutList.recommendedRevenue / cutList.totalLbs : 0;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(
    `Prices average to your recommended ${fmtCurrency2(recommendedAvg)}/lb across all cuts.`,
    margin,
    y,
  );
  y += 22;

  const colCut = margin;
  const colLbs = W * 0.66;
  const colPrice = W - margin;

  for (const group of cutList.groups) {
    if (y > H - 120) {
      doc.addPage();
      doc.setFillColor(...PAPER);
      doc.rect(0, 0, W, H, 'F');
      y = margin;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD);
    doc.text(group.label.toUpperCase(), colCut, y);
    y += 6;
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.5);
    doc.line(colCut, y, W - margin, y);
    y += 12;

    for (const cut of group.cuts) {
      if (y > H - 80) {
        doc.addPage();
        doc.setFillColor(...PAPER);
        doc.rect(0, 0, W, H, 'F');
        y = margin;
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...INK);
      doc.text(cut.name, colCut, y);

      doc.setTextColor(...MUTED);
      doc.setFontSize(9);
      doc.text(fmtLbs1(cut.estimatedLbs), colLbs, y, { align: 'right' });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      const priceColor = cut.isOverridden ? GOLD : NAVY;
      doc.setTextColor(...priceColor);
      doc.text(`${fmtCurrency2(cut.pricePerLb)} / lb`, colPrice, y, {
        align: 'right',
      });

      y += 16;
    }
    y += 8;
  }

  if (y > H - 90) {
    doc.addPage();
    doc.setFillColor(...PAPER);
    doc.rect(0, 0, W, H, 'F');
    y = margin;
  }

  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.8);
  doc.line(margin, y, W - margin, y);
  y += 18;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text('TOTAL', colCut, y);

  doc.setTextColor(...MUTED);
  doc.setFontSize(9);
  doc.text(fmtLbs(cutList.totalLbs), colLbs, y, { align: 'right' });

  doc.setFontSize(12);
  doc.setTextColor(...NAVY);
  doc.text(fmtCurrency(cutList.customRevenue), colPrice, y, { align: 'right' });
  y += 14;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(
    `Average ${fmtCurrency2(cutList.customAveragePerLb)} per lb`,
    colPrice,
    y,
    { align: 'right' },
  );
  y += 14;

  if (cutList.overriddenCount > 0) {
    const deltaText = `${cutList.delta >= 0 ? '+' : ''}${fmtCurrency(cutList.delta)} vs recommended`;
    doc.setFontSize(10);
    doc.setTextColor(...GOLD);
    doc.text(
      `${cutList.overriddenCount} ${cutList.overriddenCount === 1 ? 'cut' : 'cuts'} edited  ·  ${deltaText}`,
      colCut,
      y,
    );
  }
}

function drawSectionHeading(doc: jsPDF, x: number, y: number, label: string): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.text(label, x, y);
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.6);
  doc.line(x, y + 6, x + 400, y + 6);
  return y + 22;
}

function drawKpiStrip(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  items: Array<{ label: string; value: string }>,
): void {
  const cellW = width / items.length;
  doc.setDrawColor(...RULE);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x, y, width, 44, 6, 6, 'FD');
  items.forEach((item, i) => {
    const cx = x + cellW * i;
    if (i > 0) {
      doc.line(cx, y + 8, cx, y + 36);
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(item.label, cx + 12, y + 16);
    doc.setFontSize(14);
    doc.setTextColor(...NAVY);
    doc.text(item.value, cx + 12, y + 34);
  });
}

function drawCostSlices(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  slices: CostSlice[],
  totalCosts: number,
): number {
  const barH = 12;
  const total = totalCosts > 0 ? totalCosts : 1;
  let cursor = x;
  slices.forEach((s, i) => {
    const w = (s.value / total) * width;
    const rgb = hexToRgb(s.color);
    doc.setFillColor(...rgb);
    const r = barH / 2;
    const isFirst = i === 0;
    const isLast = i === slices.length - 1;
    if (isFirst && isLast) {
      doc.roundedRect(cursor, y, w, barH, r, r, 'F');
    } else if (isFirst) {
      doc.rect(cursor, y, w, barH, 'F');
      doc.setFillColor(...rgb);
      doc.circle(cursor + r, y + r, r, 'F');
    } else if (isLast) {
      doc.rect(cursor, y, w, barH, 'F');
      doc.circle(cursor + w - r, y + r, r, 'F');
    } else {
      doc.rect(cursor, y, w, barH, 'F');
    }
    cursor += w;
  });
  let cy = y + barH + 18;
  slices.forEach((s) => {
    const rgb = hexToRgb(s.color);
    doc.setFillColor(...rgb);
    doc.circle(x + 5, cy - 3, 4, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text(s.name, x + 18, cy);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...NAVY);
    doc.text(fmtCurrency(s.value), x + width, cy, { align: 'right' });
    cy += 16;
  });
  return cy;
}

function drawChannels(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  channels: ChannelComparison[],
): number {
  const sorted = [...channels].sort((a, b) => b.netProfit - a.netProfit);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text('CHANNEL', x, y);
  doc.text('PRICE / LB', x + width * 0.45, y, { align: 'right' });
  doc.text('NET / LB', x + width * 0.72, y, { align: 'right' });
  doc.text('TOTAL NET', x + width, y, { align: 'right' });
  let cy = y + 14;
  sorted.forEach((c, i) => {
    if (i === 0) {
      doc.setDrawColor(...GOLD);
      doc.setLineWidth(1);
      doc.line(x, cy - 8, x + width, cy - 8);
    }
    doc.setFont('helvetica', i === 0 ? 'bold' : 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    const safeName = c.name.replace(/—/g, '-');
    doc.text(safeName, x, cy + 6);
    if (c.highlight) {
      const nameWidth = doc.getTextWidth(safeName);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...GOLD);
      doc.text('FTF', x + nameWidth + 8, cy + 5);
      doc.setFont('helvetica', i === 0 ? 'bold' : 'normal');
      doc.setFontSize(10);
    }
    doc.setTextColor(...NAVY);
    doc.text(fmtCurrency2(c.pricePerLb), x + width * 0.45, cy + 6, { align: 'right' });
    doc.text(fmtCurrency2(c.netPerLb), x + width * 0.72, cy + 6, { align: 'right' });
    doc.text(fmtCurrency(c.totalNet), x + width, cy + 6, { align: 'right' });
    cy += 18;
    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.4);
    doc.line(x, cy, x + width, cy);
  });
  return cy + 8;
}

function drawAssumptions(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  input: CalculatorInput,
): number {
  const lines: Array<[string, string]> = [
    ['Packaged weight', '75% of carcass weight'],
    ['Premium production markup', input.step1.premiumProduction ? '+12% applied' : 'Not applied'],
    ['Shipping rates', 'USPS Priority Mail by zone'],
    ['Channel commissions', 'Current published rates per channel'],
  ];
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const cy = y;
  const colW = width / 2;
  lines.forEach((line, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const cx = x + col * colW;
    const ry = cy + row * 18;
    doc.setTextColor(...MUTED);
    doc.text(line[0], cx, ry);
    doc.setTextColor(...INK);
    doc.text(line[1], cx + 130, ry);
  });
  return cy + Math.ceil(lines.length / 2) * 18;
}

function hexToRgb(hex: string): [number, number, number] {
  const v = hex.replace('#', '');
  const r = parseInt(v.slice(0, 2), 16);
  const g = parseInt(v.slice(2, 4), 16);
  const b = parseInt(v.slice(4, 6), 16);
  return [r, g, b];
}
